#!/bin/bash


jupyter serverextension enable --py nbgitpuller --sys-prefix

#jupyter contrib nbextension install --user #rise
#jupyter nbextension enable splitcell/splitcell #rise
jupyter nbextension enable --py widgetsnbextension

jupyter labextension install @jupyter-widgets/jupyterlab-manager
#jupyter labextension install @jupyter-widgets/jupyterlab-sidecar
jupyter labextension install jupyter-leaflet
#jupyter labextension install jupyterlab-drawio



# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time  


